# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 10:41
from __future__ import unicode_literals

import Grader.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(blank=True, default='', max_length=100)),
                ('completed', models.CharField(choices=[('0', 'To do'), ('1', 'Doing'), ('2', 'Done')], default='0', max_length=10)),
                ('input_file', models.FileField(upload_to=Grader.models.user_input_path)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=Grader.models.user_output_path)),
                ('input_time', models.DateTimeField(auto_now_add=True)),
                ('output_time', models.DateTimeField(blank=True, null=True)),
                ('request_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
