# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-08 06:38
from __future__ import unicode_literals

import Grader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='input_file',
            field=models.FileField(upload_to=Grader.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_file',
            field=models.FileField(upload_to=Grader.models.user_directory_path),
        ),
    ]
