# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-08 06:44
from __future__ import unicode_literals

import Grader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grader', '0002_auto_20170808_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='describe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to=Grader.models.user_directory_path),
        ),
    ]
